### PR TITLE
miller dashboard Request Form UI completed

### PR DESCRIPTION
**Pull request by akashkarthick17**

### CODE REVIEW

**Review by sudharsan-gandhi — CHANGES_REQUESTED** [review]
src/app/app.component.ts ---> why used timeout? and what is purpose of this code. If it is important please make it a promise or call back function.

**Comment by akashkarthick17** [comment]
It was added to simulate the delay, in order to make sure the progress bar is working. I removed that.

**Comment by sudharsan-gandhi** [comment]
no i see only package.json been committed. please check in again. thanks for the info

**Comment by akashkarthick17** [comment]
please check now. I commited the changes.

**Pull request merged**
